
simple-string:
  g++ -Wall -Wextra -Werror -O3 -std=c++17 -pedantic-errors -DPH1 -DETYPE=std::string -DSIZE=1 simpletest.cpp -o simpletest
  ./simpletest

simple-person:
  g++ -Wall -Wextra -Werror -O3 -std=c++17 -pedantic-errors -DPH1 -DETYPE=Person -DSIZE=1 simpletest.cpp -o simpletest
  ./simpletest

btest:
  \g++ -Wall -Wextra -Og -g -std=c++17 -pedantic-errors -pthread -DPH1 btest.cpp -o btest
  ./btest -b 2> log.txt
